### ISSUE TITLE
Label "for" ID targets single-line input

### ISSUE THREAD

**Issue by leekelleher** [KevinJump/StyledTextbox#3]
I noticed a bug today, with a property's `<label for>` value.  Umbraco sets the value as the property's alias, which is expected.

However in the view, the `id=` is set on both the single-line `<input>` and multi-line `<textarea>`.

https://github.com/KevinJump/StyledTextbox/blob/master/StyledTextBox.WebSite/App_Plugins/StyledTextbox/html/styledText.html#L5

Although `ng-show` is being used to show/hide the other textbox, they are both being loaded into the DOM with `id=alias` ... and only the first one (`<input>`) is being registered.

This means that the `<label for>` doesn't work with multi-line `<textarea>`.

---

I haven't got a fix/patch for this yet. I wanted to log it here first.  I'm not expecting a quick fix or anything... I'll try to supply a patch soon.

**Comment by leekelleher** [comment]
Doh! Turns out that I added the ID attribute for the elements in PR #2 🙄 

_PR coming right up!_

**Comment by leekelleher** [comment]
Closing issue, patch available in PR #4.

**Comment by KevinJump** [comment]
keeping it open until - i get around to packaging it (or i will just forget)

**Comment by KevinJump** [comment]
Done and v1.5 released 😄
