### ISSUE TITLE
GitHub repo description

### ISSUE THREAD

**Issue by leekelleher** [KevinJump/StyledTextbox#5]
Sorry @KevinJump, my OCD is kicking in... I keep spotting the typo in the repo description:

> textbox for umbraco with css and charecter limits

It's not something I can send a PR for 😉 ... and is it okay to fix the casing too, please?

**Textbox for Umbraco with CSS and character limits**

_I'll stop now._ 😻

**Comment by KevinJump** [comment]
yeah - no worries
